In [2]:
# Dataframe is a 2D labelled data structure which will have data arranged in rows and columns
# DataFrame in Pandas help to work with tabular data, data which is in rows and column format
import pandas as pd

employees = {
    "Name": ["Denny", "Mariza", "Joshua", "Jonathan", "Jacob", "Benny"],
    "Age": [45, 18, 17, 16, 17, 43],
}

data_frame = pd.DataFrame(employees)
print(data_frame)

       Name  Age
0     Denny   45
1    Mariza   18
2    Joshua   17
3  Jonathan   16
4     Jacob   17
5     Benny   43

In [4]:
# We can add label to the index of dataframe
import pandas as pd

employees = {
    "Name": ["Denny", "Mariza", "Joshua", "Jonathan", "Jacob", "Benny"],
    "Age": [45, 18, 17, 16, 17, 43],
}
data_frame = pd.DataFrame(employees, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5", "Employee 6"])
print(data_frame)

                Name  Age
Employee 1     Denny   45
Employee 2    Mariza   18
Employee 3    Joshua   17
Employee 4  Jonathan   16
Employee 5     Jacob   17
Employee 6     Benny   43

In [11]:
# Fetch individual value from a dataframe. To do so we can use loc and iloc
import pandas as pd

employees = {
    "Name": ["Denny", "Mariza", "Joshua", "Jonathan", "Jacob", "Benny"],
    "Age": [45, 18, 17, 16, 17, 43],
}
data_frame = pd.DataFrame(employees, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5", "Employee 6"])
print(f"Using loc \nEmployee 1: {data_frame.loc['Employee 1']}")
print("============================================================")
print(f"Using iloc \nEmployee 1: {data_frame.iloc[0]}")

Using loc
Employee 1: Name    Denny
Age        45
Name: Employee 1, dtype: object
============================================================
Using iloc
Employee 1: Name    Denny
Age        45
Name: Employee 1, dtype: object

In [12]:
# Adding a new column to dataframe
import pandas as pd

employees = {
    "Name": ["Denny", "Mariza", "Joshua", "Jonathan", "Jacob", "Benny"],
    "Age": [45, 18, 17, 16, 17, 43],
}
data_frame = pd.DataFrame(employees, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5", "Employee 6"])
data_frame['Hobbies'] = ['Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family']
print(data_frame)

                Name  Age                 Hobbies
Employee 1     Denny   45  Spend time with Family
Employee 2    Mariza   18  Spend time with Family
Employee 3    Joshua   17  Spend time with Family
Employee 4  Jonathan   16  Spend time with Family
Employee 5     Jacob   17  Spend time with Family
Employee 6     Benny   43  Spend time with Family

In [17]:
# Adding new row to dataframe
import pandas as pd

employees = {
    "Name": ["Denny", "Mariza", "Joshua", "Jonathan", "Jacob", "Benny"],
    "Age": [45, 18, 17, 16, 17, 43],
}
data_frame = pd.DataFrame(employees, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5", "Employee 6"])
data_frame['Hobbies'] = ['Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family']

# We create a new data frame and then concatenate with original one
employee = {
    "Name": "Varughese",
    "Age": 75,
    "Hobbies": "Spend time with Family"
}
new_row = pd.DataFrame([employee], index=['Employee 7'])
data_frame = pd.concat([data_frame, new_row])
print(data_frame)

                 Name  Age                 Hobbies
Employee 1      Denny   45  Spend time with Family
Employee 2     Mariza   18  Spend time with Family
Employee 3     Joshua   17  Spend time with Family
Employee 4   Jonathan   16  Spend time with Family
Employee 5      Jacob   17  Spend time with Family
Employee 6      Benny   43  Spend time with Family
Employee 7  Varughese   75  Spend time with Family

In [1]:
# Adding multiple rows to dataframe
import pandas as pd

employees = {
    "Name": ["Denny", "Mariza", "Joshua", "Jonathan", "Jacob", "Benny"],
    "Age": [45, 18, 17, 16, 17, 43],
}
data_frame = pd.DataFrame(employees, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5", "Employee 6"])
data_frame['Hobbies'] = ['Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family']

# When we need to add multiple rows the pass array of dictionary to DataFrame and then concatenate that dataframe with original one
new_employees = [
    {
        "Name": "Varughese",
        "Age": 75,
        "Hobbies": "Spend time with Family"
    },
    {
        "Name": "Lissy",
        "Age": 65,
        "Hobbies": "Spend time with Family",
    }
]

new_frames = pd.DataFrame(new_employees, index=["Employee 7", "Employee 8"])
data_frame = pd.concat([data_frame, new_frames])
print(data_frame)

                 Name  Age                 Hobbies
Employee 1      Denny   45  Spend time with Family
Employee 2     Mariza   18  Spend time with Family
Employee 3     Joshua   17  Spend time with Family
Employee 4   Jonathan   16  Spend time with Family
Employee 5      Jacob   17  Spend time with Family
Employee 6      Benny   43  Spend time with Family
Employee 7  Varughese   75  Spend time with Family
Employee 8      Lissy   65  Spend time with Family

In [3]:
# head() and tail()
import pandas as pd

employees = {
    "Name": ["Denny", "Mariza", "Joshua", "Jonathan", "Jacob", "Benny"],
    "Age": [45, 18, 17, 16, 17, 43],
}
data_frame = pd.DataFrame(employees, index=["Employee 1", "Employee 2", "Employee 3", "Employee 4", "Employee 5", "Employee 6"])
data_frame['Hobbies'] = ['Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family', 'Spend time with Family']

# When we need to add multiple rows the pass array of dictionary to DataFrame and then concatenate that dataframe with original one
new_employees = [
    {
        "Name": "Varughese",
        "Age": 75,
        "Hobbies": "Spend time with Family"
    },
    {
        "Name": "Lissy",
        "Age": 65,
        "Hobbies": "Spend time with Family",
    }
]

new_frames = pd.DataFrame(new_employees, index=["Employee 7", "Employee 8"])
data_frame = pd.concat([data_frame, new_frames])
data_frame.head() # Returns first 5 rows

                Name  Age                 Hobbies
Employee 1     Denny   45  Spend time with Family
Employee 2    Mariza   18  Spend time with Family
Employee 3    Joshua   17  Spend time with Family
Employee 4  Jonathan   16  Spend time with Family
Employee 5     Jacob   17  Spend time with Family

In [11]:
data_frame.tail() # Returns last 5 rows

                 Name  Age                 Hobbies
Employee 4   Jonathan   16  Spend time with Family
Employee 5      Jacob   17  Spend time with Family
Employee 6      Benny   43  Spend time with Family
Employee 7  Varughese   75  Spend time with Family
Employee 8      Lissy   65  Spend time with Family

In [13]:
data_frame.head(2) # Returns first 2 rows

              Name  Age                 Hobbies
Employee 1   Denny   45  Spend time with Family
Employee 2  Mariza   18  Spend time with Family

In [15]:
data_frame.tail(2) # Returns last 2 rows

                 Name  Age                 Hobbies
Employee 7  Varughese   75  Spend time with Family
Employee 8      Lissy   65  Spend time with Family

In [18]:
data_frame.shape # Returns shape of the data frame

(8, 3)

In [21]:
data_frame.describe() # Descibes details like count, mean, std, min, max of data frame

             Age
count   8.000000
mean   37.000000
std    23.694484
min    16.000000
25%    17.000000
50%    30.500000
75%    50.000000
max    75.000000

In [22]:
data_frame.info()  # Gives information about the data frame

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, Employee 1 to Employee 8
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      object
 1   Age      8 non-null      int64
 2   Hobbies  8 non-null      object
dtypes: int64(1), object(2)
memory usage: 256.0+ bytes

In [25]:
# Fetch 3 Names from above data frame
data_frame['Name'].head(3)

Employee 1     Denny
Employee 2    Mariza
Employee 3    Joshua
Name: Name, dtype: object

In [28]:
# When you fetch single column from a data frame then it will be a series
type(data_frame['Name'])

pandas.core.series.Series

In [30]:
# Fetch multiple columns from data frame
data_frame[['Name', 'Age']]

                 Name  Age
Employee 1      Denny   45
Employee 2     Mariza   18
Employee 3     Joshua   17
Employee 4   Jonathan   16
Employee 5      Jacob   17
Employee 6      Benny   43
Employee 7  Varughese   75
Employee 8      Lissy   65

In [32]:
# When you fetch multiple columns from data from then its type will be DataFrame
type(data_frame[['Name', 'Age']])

pandas.core.frame.DataFrame

In [5]:
# get data for first 4 Name and Age
data_frame[['Name', 'Age']].iloc[0:4]

                Name  Age
Employee 1     Denny   45
Employee 2    Mariza   18
Employee 3    Joshua   17
Employee 4  Jonathan   16

In [11]:
data_frame.loc[['Employee 1', 'Employee 2']]

              Name  Age                 Hobbies
Employee 1   Denny   45  Spend time with Family
Employee 2  Mariza   18  Spend time with Family

In [12]:
data_frame[['Name']]

                 Name
Employee 1      Denny
Employee 2     Mariza
Employee 3     Joshua
Employee 4   Jonathan
Employee 5      Jacob
Employee 6      Benny
Employee 7  Varughese
Employee 8      Lissy