In [3]:
import pandas as pd

sales_data = pd.read_csv('data/sales_data.csv')
sales_data

           Date        Product        Category  Price  Quantity
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel    NaN       NaN
3    2023-01-27            NaN         Apparel    NaN       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

[102 rows x 5 columns]

In [10]:
# Display first 10 rows and summary statistics (mean, std, etc) of numeric columns
data_frame = sales_data.select_dtypes(include=['number']).head(10).describe()
data_frame

            Price  Quantity
count   10.000000  9.000000
mean   249.500000  4.666667
std    208.720041  2.121320
min     27.000000  1.000000
25%     74.250000  3.000000
50%    190.500000  5.000000
75%    396.500000  6.000000
max    632.000000  8.000000

In [35]:
# Check for missing values in each column.
sales_data.isnull().sum()

Date        0
Product     0
Category    0
Price       1
Quantity    1
dtype: int64

In [37]:
# Calculate the percentage of missing data
missing_percentage = (sales_data.isnull().sum()/len(sales_data)) * 100
missing_percentage

Date        0.000000
Product     0.000000
Category    0.000000
Price       0.990099
Quantity    0.990099
dtype: float64

In [16]:
# Filter columns with any missing
sales_data.columns[sales_data.isnull().any()]

Index(['Quantity'], dtype='object')

In [20]:
# Rename column 'Price' to 'Unit Price' and 'Date' to 'Sales Date'
new_sales_data = sales_data.rename(columns={'Price': 'Unit Price', 'Date': 'Sales Date'})
new_sales_data

     Sales Date            Product        Category  Unit Price  Quantity
0    2023-01-25               Sofa       Furniture          28       6.0
1    2023-01-26       Denim Jacket         Apparel         180       5.0
2    2023-01-27       Denim Jacket         Apparel         180       NaN
3    2023-02-04            Pen Set      Stationery         486       1.0
4    2023-02-05  Desktop Organizer      Stationery          39       6.0
..          ...                ...             ...         ...       ...
96   2023-12-10           Backpack      Stationery         332       2.0
97   2023-12-11            Pen Set      Stationery         660       2.0
98   2023-12-14          Air Fryer  Home & Kitchen         804       2.0
99   2023-12-17       Dining Table       Furniture         954       3.0
100  2023-12-28      Standing Desk       Furniture         409       6.0

[101 rows x 5 columns]

In [23]:
# Select all rows where the Category is "Electronics" and the Quantity is greater than 5.
electronics_sales = sales_data[(sales_data['Category'] == 'Electronics') & (sales_data['Quantity'] > 5)]
electronics_sales

          Date            Product     Category  Price  Quantity
12  2023-03-07         Smartphone  Electronics    756      10.0
20  2023-03-24             Laptop  Electronics    640       7.0
29  2023-04-11  Bluetooth Speaker  Electronics    942      10.0
44  2023-06-15             Laptop  Electronics    330       9.0
58  2023-08-02         Smartwatch  Electronics    214       6.0
76  2023-09-21  Bluetooth Speaker  Electronics    621       6.0

In [27]:
# Select only the Product and Price columns for the first 50 rows
details_1 = sales_data[['Product', 'Price']].head(50)
details_1

              Product  Price
0                Sofa     28
1        Denim Jacket    180
2        Denim Jacket    180
3             Pen Set    486
4   Desktop Organizer     39
5     Leather Journal    432
6        Sticky Notes     27
7              Hoodie    290
8              Hoodie    201
9           Bookshelf    632
10          Air Fryer    461
11             Hoodie     49
12         Smartphone    756
13       Coffee Maker    168
14               Sofa    309
15             Hoodie     18
16            Blender    305
17     Vacuum Cleaner    886
18    Ergonomic Chair    292
19    Leather Journal    964
20             Laptop    640
21          Air Fryer    573
22       Sticky Notes    682
23            Pen Set    508
24            Pen Set    529
25            Pen Set    950
26       Baseball Cap    208
27       Sticky Notes    914
28           Backpack    196
29  Bluetooth Speaker    942
30            Toaster     35
31    Leather Journal    218
32  Desktop Organizer    660
33       Sticky Notes    844
34            T-Shirt    465
35       Dining Table    916
36     Vacuum Cleaner    376
37            Toaster    874
38            Pen Set    729
39            Pen Set    830
40       Sticky Notes    782
41       Dining Table    911
42            Toaster    249
43  Desktop Organizer     50
44             Laptop    330
45       Denim Jacket    960
46               Sofa    935
47             Hoodie    215
48           Backpack    179
49     Vacuum Cleaner    803

In [30]:
# Use .iloc to select the value in the 3rd row and 2nd column
sales_data.iloc[2, 1]

'Denim Jacket'

In [32]:
# Use .iloc to select the value in the 3rd row and 2nd and 3rd column
sales_data.iloc[2, [1,2]]

Product     Denim Jacket
Category         Apparel
Name: 2, dtype: object

In [20]:
# If the Price column has missing values, how do you fill them with the median price of the entire column?
sales_data = pd.read_csv('data/sales_data.csv')
print(sales_data)
price_median = sales_data['Price'].median()
print(f'Price Median: {price_median}')
sales_data['Price'] = sales_data['Price'].fillna(price_median)
sales_data
# Why Use Median Instead of Mean?
# While dealing with prices median is used over mean because
# 1) It is robust to outliers. 
#   That means imagine 5 people in a room earning 50000/year. So mean = 50000 and median = 50000.
#   Lets say billionare enters the room, then the income of that person will be an outlier compared to others. 
#   So value mean will become billions of dollars but median remains 50000. 
#   That means mean is sensitive to outliers but median is robust to outliers.
# 2) It ensures the filled values are more "typical" of your existing data. 
#    In data science, "typical" means that the new values shouldn't be "weird" or "extreme" compared to what is already there. 
#    They should blend into the existing distribution so they don't skew your final analysis.

           Date        Product        Category  Price  Quantity
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel    NaN       NaN
3    2023-01-27            NaN         Apparel    NaN       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

[102 rows x 5 columns]
Price Median: 486.0

           Date        Product        Category  Price  Quantity
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel  486.0       NaN
3    2023-01-27            NaN         Apparel  486.0       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

[102 rows x 5 columns]

In [22]:
# Fill multiple numeric columns with their respective medians for missing values
sales_data = pd.read_csv('data/sales_data.csv')
print(sales_data)
sales_data = sales_data.fillna(sales_data.median(numeric_only=True))
sales_data

           Date        Product        Category  Price  Quantity
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel    NaN       NaN
3    2023-01-27            NaN         Apparel    NaN       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

[102 rows x 5 columns]

           Date        Product        Category  Price  Quantity
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel  486.0       5.0
3    2023-01-27            NaN         Apparel  486.0       5.0
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

[102 rows x 5 columns]

In [4]:
# Drop all rows where the Product name is null?
sales_data = pd.read_csv('data/sales_data.csv')
print(sales_data)
sales_data = sales_data.dropna(subset=['Product'])
print(sales_data)

           Date        Product        Category  Price  Quantity
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel    NaN       NaN
3    2023-01-27            NaN         Apparel    NaN       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

[102 rows x 5 columns]
           Date            Product        Category  Price  Quantity
0    2023-01-25               Sofa       Furniture   28.0       6.0
1    2023-01-26       Denim Jacket         Apparel  180.0       5.0
2    2023-01-27       Denim Jacket         Apparel    NaN       NaN
4    2023-02-04            Pen Set      Stationery  486.0       1.0
5    2023-02-05  Desktop Organizer      Stationery   39.0       6.0
..          ...                ...             ...    ...       ...
97   2023-12-10           Backpack      Stationery  332.0       2.0
98   2023-12-11            Pen Set      Stationery  660.0       2.0
99   2023-12-14          Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17       Dining Table       Furniture  954.0       3.0
101  2023-12-28      Standing Desk       Furniture  409.0       6.0

[101 rows x 5 columns]

In [71]:
# Convert the Date column from a string (object) type to a proper datetime object.
initial_type = type(sales_data['Date'].iloc[0])
print(f'Before conversion : {initial_type}')
sales_data['Date'] = pd.to_datetime(sales_data['Date'])
converted_type = type(sales_data['Date'].iloc[0])
print(f'After conversion : {converted_type}')

Before conversion : <class 'pandas._libs.tslibs.timestamps.Timestamp'>
After conversion : <class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [90]:
# Find the total revenue (Price * Quantity) for each Category.
# Create a new column 'Revenue' in sales_data
sales_data['Revenue'] = sales_data['Price'] * sales_data['Quantity']

revenue_by_category = sales_data.groupby('Category')
print(revenue_by_category['Revenue'].sum())

Category
Apparel           2966.0
Electronics       7560.0
Furniture         2064.0
Home & Kitchen     461.0
Stationery        3528.0
Name: Revenue, dtype: float64
count       5.000000
mean     3315.800000
std      2640.904618
min       461.000000
25%      2064.000000
50%      2966.000000
75%      3528.000000
max      7560.000000
Name: Revenue, dtype: float64

In [6]:
# Count how many unique products are sold in each category.
group_by_category = sales_data.groupby('Category')
print("Count using nunique()")
print(group_by_category['Product'].nunique())
print("=================================================")
print("Count using count()")
print(group_by_category['Product'].count()) # This will not be correct
#count(): Counts every row in that category (including duplicates). If "Apple" appears 5 times, it counts as 5.
#nunique(): Counts only the distinct names. If "Apple" appears 5 times, it counts as 1.

Count using nunique()
Category
Apparel           5
Electronics       5
Furniture         5
Home & Kitchen    5
Stationery        5
Name: Product, dtype: int64
=================================================
Count using count()
Category
Apparel           18
Electronics       14
Furniture         18
Home & Kitchen    22
Stationery        29
Name: Product, dtype: int64

In [15]:
# Get the maximum and minimum price for each category in a single command using .agg().
group_by_category = sales_data.groupby('Category')
price_by_category = group_by_category['Price']
print(price_by_category.agg(['min', 'max']))

# We can do this in single command as
sales_data.groupby('Category')['Price'].agg(['min', 'max'])

                  min    max
Category
Apparel          18.0  960.0
Electronics     185.0  990.0
Furniture        28.0  954.0
Home & Kitchen   35.0  896.0
Stationery       27.0  964.0

                  min    max
Category
Apparel          18.0  960.0
Electronics     185.0  990.0
Furniture        28.0  954.0
Home & Kitchen   35.0  896.0
Stationery       27.0  964.0

In [24]:
# Create a new column called Discount_Price that is 90% of the original Price.
sales_data = pd.read_csv('data/sales_data.csv')
sales_data['Discount_Price'] = sales_data['Price'] * (90/100)
sales_data

,Date,Product,Category,Price,Quantity,Discount_Price
0,2023-01-25,Sofa,Furniture,28.0,6.0,25.2
1,2023-01-26,Denim Jacket,Apparel,180.0,5.0,162.0
2,2023-01-27,Denim Jacket,Apparel,NaN,NaN,NaN
3,2023-01-27,NaN,Apparel,NaN,NaN,NaN
4,2023-02-04,Pen Set,Stationery,486.0,1.0,437.4
...,...,...,...,...,...,...
97,2023-12-10,Backpack,Stationery,332.0,2.0,298.8
98,2023-12-11,Pen Set,Stationery,660.0,2.0,594.0
99,2023-12-14,Air Fryer,Home & Kitchen,804.0,2.0,723.6
100,2023-12-17,Dining Table,Furniture,954.0,3.0,858.6
101,2023-12-28,Standing Desk,Furniture,409.0,6.0,368.1

In [28]:
# Creating column using assign(). Assign will add new column and return a new data frame so your original data frame is not
# changed
sales_data = pd.read_csv('data/sales_data.csv')
new_sales_data = sales_data.assign(Discount_price = sales_data['Price'] * (90/100))
print(new_sales_data) # New column is added
print('---------------------------------------------------------')
print(sales_data)

           Date        Product        Category  Price  Quantity  \
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel    NaN       NaN
3    2023-01-27            NaN         Apparel    NaN       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

     Discount_price
0              25.2
1             162.0
2               NaN
3               NaN
4             437.4
..              ...
97            298.8
98            594.0
99            723.6
100           858.6
101           368.1

[102 rows x 6 columns]
---------------------------------------------------------
           Date        Product        Category  Price  Quantity
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel    NaN       NaN
3    2023-01-27            NaN         Apparel    NaN       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

[102 rows x 5 columns]

In [36]:
# Apply discount to a specific category
import numpy as np
sales_data = pd.read_csv('data/sales_data.csv')
new_sales_data = sales_data
new_sales_data['Discount_Price'] = np.where(sales_data['Category'] == 'Electronics', 
                                            sales_data['Price'] * (90/100),
                                            sales_data['Price']
                                           )

# Discount price is calculated only for 'Electronics' category for other categories it will be same as price value
print(new_sales_data[sales_data['Category'] == 'Electronics']) 
print('----------------------------------------------')
print(new_sales_data)

          Date              Product     Category  Price  Quantity  \
13  2023-03-07           Smartphone  Electronics  756.0      10.0
21  2023-03-24               Laptop  Electronics  640.0       7.0
30  2023-04-11    Bluetooth Speaker  Electronics  942.0      10.0
45  2023-06-15               Laptop  Electronics  330.0       9.0
52  2023-07-11    Bluetooth Speaker  Electronics  990.0       2.0
54  2023-07-17           Smartphone  Electronics  242.0       4.0
58  2023-07-25           Smartphone  Electronics  185.0       3.0
59  2023-08-02           Smartwatch  Electronics  214.0       6.0
63  2023-08-18    Bluetooth Speaker  Electronics  661.0       4.0
64  2023-08-20           Smartphone  Electronics  866.0       2.0
65  2023-08-20               Laptop  Electronics  640.0       3.0
77  2023-09-21    Bluetooth Speaker  Electronics  621.0       6.0
81  2023-10-11               Laptop  Electronics  266.0       2.0
95  2023-12-03  Wireless Headphones  Electronics  688.0       5.0

    Discount_Price
13           680.4
21           576.0
30           847.8
45           297.0
52           891.0
54           217.8
58           166.5
59           192.6
63           594.9
64           779.4
65           576.0
77           558.9
81           239.4
95           619.2
----------------------------------------------
           Date        Product        Category  Price  Quantity  \
0    2023-01-25           Sofa       Furniture   28.0       6.0
1    2023-01-26   Denim Jacket         Apparel  180.0       5.0
2    2023-01-27   Denim Jacket         Apparel    NaN       NaN
3    2023-01-27            NaN         Apparel    NaN       NaN
4    2023-02-04        Pen Set      Stationery  486.0       1.0
..          ...            ...             ...    ...       ...
97   2023-12-10       Backpack      Stationery  332.0       2.0
98   2023-12-11        Pen Set      Stationery  660.0       2.0
99   2023-12-14      Air Fryer  Home & Kitchen  804.0       2.0
100  2023-12-17   Dining Table       Furniture  954.0       3.0
101  2023-12-28  Standing Desk       Furniture  409.0       6.0

     Discount_Price
0              28.0
1             180.0
2               NaN
3               NaN
4             486.0
..              ...
97            332.0
98            660.0
99            804.0
100           954.0
101           409.0

[102 rows x 6 columns]

In [40]:
# Capitalize every string in the product column
sales_data = pd.read_csv('data/sales_data.csv')
sales_data['Product'].str.capitalize()

0               Sofa
1       Denim jacket
2       Denim jacket
3                NaN
4            Pen set
           ...
97          Backpack
98           Pen set
99         Air fryer
100     Dining table
101    Standing desk
Name: Product, Length: 102, dtype: object

In [44]:
# Use a lamda function to capitalize every string in the product column
# For this purpose we can use apply(). With this we can pass a lambda function and apply it on each value of the column
sales_data = pd.read_csv('data/sales_data.csv')
sales_data = sales_data.dropna() # We need to clean the data first
sales_data['Product'] = sales_data['Product'].apply(lambda x: x.capitalize())
sales_data['Product']

0                   Sofa
1           Denim jacket
4                Pen set
5      Desktop organizer
6        Leather journal
             ...
97              Backpack
98               Pen set
99             Air fryer
100         Dining table
101        Standing desk
Name: Product, Length: 100, dtype: object