In [2]:
import pandas as pd

In [34]:
experience = [1,2,3,4,5]
#salary
salary = [3000,4000,5000,6000,7000]
df = pd.DataFrame({
    "Experience": experience,
    "Salary": salary
})
df

   Experience  Salary
0           1    3000
1           2    4000
2           3    5000
3           4    6000
4           5    7000

In [35]:
#linear regression
from sklearn.linear_model import LinearRegression
X = df[["Experience"]]
Y = df["Salary"]

In [36]:
X

   Experience
0           1
1           2
2           3
3           4
4           5

In [37]:
Y

0    3000
1    4000
2    5000
3    6000
4    7000
Name: Salary, dtype: int64

In [38]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [39]:
new_data = pd.DataFrame({
    "Experience": [60]
})
print(model.predict(new_data))

[62000.]

In [41]:
#Decision tree
area = [800, 1000, 1200, 1500, 1800, 2000, 2200, 2500]
rooms = [2, 2, 3, 3, 4, 4, 4, 5]
age = [20, 15, 10, 8, 5, 3, 2, 1]
#pricing
price = [30, 40, 50, 65, 80, 90, 100, 120]
import pandas as pd
df = pd.DataFrame({
    "Area": area,
    "Rooms": rooms,
    "Age": age,
    "Price": price
})
df

   Area  Rooms  Age  Price
0   800      2   20     30
1  1000      2   15     40
2  1200      3   10     50
3  1500      3    8     65
4  1800      4    5     80
5  2000      4    3     90
6  2200      4    2    100
7  2500      5    1    120

In [42]:
from sklearn.tree import DecisionTreeRegressor
X = df[["Area", "Rooms", "Age"]]
Y = df["Price"]
X
# model = DecisionTreeRegressor

   Area  Rooms  Age
0   800      2   20
1  1000      2   15
2  1200      3   10
3  1500      3    8
4  1800      4    5
5  2000      4    3
6  2200      4    2
7  2500      5    1

In [43]:
Y

0     30
1     40
2     50
3     65
4     80
5     90
6    100
7    120
Name: Price, dtype: int64

In [45]:
model = DecisionTreeRegressor(max_depth=3)
model.fit(X,Y)

DecisionTreeRegressor(max_depth=3)

In [49]:
prediction = model.predict([[1200, 5, 1]])
print("Predicted value:", prediction)

Predicted value: [120.]

C:\Users\akshu\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [53]:
## Random forest regressor
# predict student marks based on :  sleep hours, study hours, number of practice test

study_hours = [1,2,3,4,5,6,7,8]
sleep_hours = [8,7,7,6,6,5,5,4]
practice_tests = [0,1,1,2,2,3,3,4]

marks = [30,40,50,70,60,80,85,90]

import pandas as pd
df = pd.DataFrame({ 
    "StudyHours": study_hours,
    "SleepHours": sleep_hours,
    "PracticeTests": practice_tests,
    "Marks": marks
})
df

   StudyHours  SleepHours  PracticeTests  Marks
0           1           8              0     30
1           2           7              1     40
2           3           7              1     50
3           4           6              2     70
4           5           6              2     60
5           6           5              3     80
6           7           5              3     85
7           8           4              4     90

In [54]:
# #inference: 
# More study hours -> more marks
# More practice test -> better performance
# Too much sleep -> maybe less study
# model will learn combined effect

In [56]:
from sklearn.tree import DecisionTreeRegressor
X = df[["StudyHours", "SleepHours", "PracticeTests"]]
y = df["Marks"]
tree_model = DecisionTreeRegressor(max_depth=3)
tree_model.fit(X,y)

DecisionTreeRegressor(max_depth=3)

In [58]:
# Random forest 

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=50,
    max_depth=3,
    random_state=42
)
rf_model.fit(X,y)

RandomForestRegressor(max_depth=3, n_estimators=50, random_state=42)

In [59]:
# prediction 
# example student:
# study = 5 hours , sleep = 6 hours , practice = 2 test

tree_pred = tree_model.predict([[5,6,2]])
rf_pred = rf_model.predict([[5,6,2]])

print("Decision Tree: ", tree_pred)
print("Random Forest: ", rf_pred)

Decision Tree:  [60.]
Random Forest:  [62.5]

C:\Users\akshu\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
C:\Users\akshu\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [61]:
#tensor flow example
X = [[1000], [1500], [2000]]
y = [10,15,20]
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10,activation='relu'),
    tf.keras.layers.Dense(1)
])
model.compile(optimizer='adam', loss='mse')
model.fit(X,y, epochs=10)

ModuleNotFoundError: No module named 'tensorflow'