In [8]:
# Training based on Linear Regression. Used for predicting continuous numerical values based on linear relationships
# Its basically use the formula of linear graph, y = mx + b
# where 'm' is the interval between x values and 'x' will be individual x values and 'b' will be starting value of x

import pandas as pd

experience = [1, 2, 3, 4, 5]
salary = [3000, 4000, 5000, 6000, 7000]

data_frame = pd.DataFrame({
    'Experience': experience,
    'Salary': salary,
})

data_frame
# Now we will train the model. We are going to use linear regression algorithm

   Experience  Salary
0           1    3000
1           2    4000
2           3    5000
3           4    6000
4           5    7000

In [11]:
from sklearn.linear_model import LinearRegression # Here we are importing the algorithm of LinearRegression. Which will be used for creating model

X = data_frame[['Experience']]
Y = data_frame[['Salary']]

In [13]:
X

   Experience
0           1
1           2
2           3
3           4
4           5

In [16]:
Y

   Salary
0    3000
1    4000
2    5000
3    6000
4    7000

In [19]:
model = LinearRegression() # This will create a dummy model but no training is done. Basically its like a new born baby which doesnt have any knowledge
model.fit(X, Y) # When this step completes we get model which can be used for prediction and decision making

LinearRegression()

In [25]:
# Our scenario is salary range of employee based on their experience.
# Now we can predict what will be the salary of an employee with experience of N years. To do so
number_of_years = int(input('Number of Years'))
predicted_salary = model.predict(pd.DataFrame({'Experience': [number_of_years]}))
print(f'Salary of employee with {number_of_years}: {predicted_salary}')

Number of Years 10

Salary of employee with 10: [[12000.]]