In [2]:
import pandas as pd

data = {
    "Age":        [22, 25, 30, 35, 40, 28, 32, 45, 50, 23, 27, 31, 38, 42, 29],
    "Gender":     [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    "Income":     [20, 25, 40, 60, 80, 35, 50, 90, 100, 22, 30, 45, 70, 85, 38],
    "TimeSpent":  [5, 10, 15, 20, 25, 12, 18, 30, 35, 8, 14, 16, 22, 28, 13],
    "Season":     [0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
    "Product": [
        "TShirt", "TShirt", "Jeans", "Jacket", "Jacket",
        "Jeans", "Jacket", "Jacket", "Jacket", "TShirt",
        "TShirt", "Jeans", "Jacket", "Jacket", "Jeans"
    ]
}

data_frame = pd.DataFrame(data)
data_frame

    Age  Gender  Income  TimeSpent  Season Product
0    22       0      20          5       0  TShirt
1    25       1      25         10       0  TShirt
2    30       0      40         15       1   Jeans
3    35       1      60         20       1  Jacket
4    40       0      80         25       1  Jacket
5    28       1      35         12       0   Jeans
6    32       0      50         18       1  Jacket
7    45       1      90         30       1  Jacket
8    50       0     100         35       1  Jacket
9    23       1      22          8       0  TShirt
10   27       0      30         14       0  TShirt
11   31       1      45         16       1   Jeans
12   38       0      70         22       1  Jacket
13   42       1      85         28       1  Jacket
14   29       0      38         13       0   Jeans

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
X = data_frame[["Age", "Gender", "Income", "TimeSpent","Season"]]
y = data_frame["Product"]

In [8]:
#creating the testing and training data
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

# from the dataset we have split the data into training (80%) and test (20%)
X_train

    Age  Gender  Income  TimeSpent  Season
13   42       1      85         28       1
5    28       1      35         12       0
8    50       0     100         35       1
2    30       0      40         15       1
1    25       1      25         10       0
14   29       0      38         13       0
4    40       0      80         25       1
7    45       1      90         30       1
10   27       0      30         14       0
12   38       0      70         22       1
3    35       1      60         20       1
6    32       0      50         18       1

In [10]:
y_train

13    Jacket
5      Jeans
8     Jacket
2      Jeans
1     TShirt
14     Jeans
4     Jacket
7     Jacket
10    TShirt
12    Jacket
3     Jacket
6     Jacket
Name: Product, dtype: object

In [12]:
X_test

    Age  Gender  Income  TimeSpent  Season
9    23       1      22          8       0
11   31       1      45         16       1
0    22       0      20          5       0

In [15]:
y_test

9     TShirt
11     Jeans
0     TShirt
Name: Product, dtype: object

In [17]:
model = KNeighborsClassifier(n_neighbors=3)  #n_neighbors : number of nearest data points the model looks at before making a prediction
model.fit(X_train, y_train) # Here it doesnt do analysis of data instead it stores it into memory and does the calculation at the time of prediction

KNeighborsClassifier(n_neighbors=3)

In [19]:
input = pd.DataFrame({
    'Age': [29],
    'Gender': [1],
    'Income': [45],
    'TimeSpent': [15],
    'Season': [1]
})
prediction = model.predict(input)
print("Predicted Product:", prediction)

Predicted Product: ['Jeans']

In [21]:
# Calculate the accuracy
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 1.0